name: Myanmar Earthquake ETL Pipeline
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"  # Runs every minute
  workflow_dispatch:

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the ETL script
      - name: Run ETL script
        run: |
          python main.py
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

      # Step 5: Commit updated files (save_ids.txt)
      - name: Commit updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ids.txt
          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "Update ids.txt with new IDs"
          git push